User's scenario
Ann-Ageeva/Sound-recognition pull request #14
Opened 2020-03-04 15:06 UTC by Ann-Ageeva

2020-03-04 20:34 UTC, AMyachev commented
Илья, после ревью не закрывай PR. Я тоже посмотрю

2020-03-07 20:12 UTC, AMyachev commented
@Ann-Ageeva добавь также шаблон оператора в этом реквесте

2020-03-16 11:21 UTC, AMyachev requested changes

2020-03-16 11:21 UTC, AMyachev commented on docs/use-case.md
> +ПО «Dron sound detection» предназначено для обнаружения дрона и определения его направления в радиусе около 30-ти метров. Данное ПО может использоваться предприятиями, которым необходима усиленная ох
Лучше взять эту часть из ТЗ; глава (или пункт) - назначение

2020-03-16 11:21 UTC, AMyachev commented on docs/use-case.md
> +ПО «Dron sound detection» предназначено для обнаружения дрона и определения его направления в радиусе около 30-ти метров. Данное ПО может использоваться предприятиями, которым необходима усиленная ох
Почему "30-ти метров"?

2020-03-16 11:21 UTC, AMyachev commented on docs/use-case.md
> +Результатом работы ПО является расчет вероятности наличия дрона в заданном радиусе и, при положительном результате, направление его движения. Разработка данного ПО поможет обезопасить территорию от н
"Направление его движения" - это может означать, что мы определяем траекторию движения дрона, но мы этого не делаем. Мы всего лишь находим направление того, откуда идёт звук.

2020-03-16 11:21 UTC, AMyachev commented on docs/use-case.md
> +3.2. ЗАПУСК ПО В КАЧЕСТВЕ КОНСОЛЬНОГО ПРИЛОЖЕНИЯ	7
Что за цифры в конце каждой строчки?

2020-03-16 11:21 UTC, AMyachev commented on docs/use-case.md
> +ПО «Dron sound detection» предназначено для обнаружения дрона и определения его направления в радиусе около 30-ти метров. Данное ПО может использоваться предприятиями, которым необходима усиленная ох
Те же проблемы: "его направления" и 30 метров. Синхронизуй этот пункт с аналогичным в ТЗ. Мне кажется в назначении не нужно писать о деталях работы системы.

2020-03-16 11:21 UTC, AMyachev commented on docs/use-case.md
> +	Отличать звук дрона от других шумов в радиусе 30-ти метров;
уже третье упоминание 30 метров)

2020-03-16 11:21 UTC, AMyachev commented on docs/use-case.md
> +	Определять наличие дрона в данном радиусе;
а мы все 360 градусов будем мониторить? Если нет, то надо уточнить сектор

2020-03-16 11:21 UTC, AMyachev commented on docs/use-case.md
> +	Определять примерное направление движения дрона, относительно точки с устройством, на котором установлено данное ПО.
мы не определяем направление движения дрона

2020-03-16 11:21 UTC, AMyachev commented on docs/use-case.md
> +Для функционирования ПО детектирования необходимо: устройство записи звука, север, сеть, соединяющая устройства. Для осуществления детектирования online также понадобится мини-компьютер Raspberry Pi,
про Raspberry PI не стоит упоминать. Мы лучше опишем интерфейсно, что нам нужно от устройства, делающего записи.

2020-03-16 11:21 UTC, AMyachev commented
@Merilla сделай ревью 3 пункта плиз

2020-03-16 12:33 UTC, Ann-Ageeva commented on docs/use-case.md
> +	Определять наличие дрона в данном радиусе;
я думала, что все 360. разве определили, что 180?

2020-03-16 12:34 UTC, Ann-Ageeva commented on docs/use-case.md
> +3.2. ЗАПУСК ПО В КАЧЕСТВЕ КОНСОЛЬНОГО ПРИЛОЖЕНИЯ	7
уберу, это страницы по содержанию.

2020-03-16 12:36 UTC, Ann-Ageeva commented on docs/use-case.md
> +ПО «Dron sound detection» предназначено для обнаружения дрона и определения его направления в радиусе около 30-ти метров. Данное ПО может использоваться предприятиями, которым необходима усиленная ох
напишу, как ТЗ. но вообще - это примерное расстояние, на котором у нас должно всё работать, если учитывать, чувствительность микрофона и "умеренный шум". и нам просто вроде говорили уточнить хотя бы примерное расстояние работы.

2020-03-16 13:02 UTC, Ann-Ageeva commented on docs/use-case.md
> +Для функционирования ПО детектирования необходимо: устройство записи звука, север, сеть, соединяющая устройства. Для осуществления детектирования online также понадобится мини-компьютер Raspberry Pi,
не очень поняла, почему не стоит? у нас же по-разному будет работать система на удаленке, и в реальном времени. или как?

2020-03-16 14:22 UTC, AMyachev commented on docs/use-case.md
> +Для функционирования ПО детектирования необходимо: устройство записи звука, север, сеть, соединяющая устройства. Для осуществления детектирования online также понадобится мини-компьютер Raspberry Pi,
а вдруг пользователя захотят использовать arduino или ещё что-нибудь. Мы можем сейчас не ограничивать их.

2020-03-16 14:52 UTC, AMyachev commented on docs/use-case.md
> +ПО «Dron sound detection» предназначено для обнаружения дрона и определения его направления в радиусе около 30-ти метров. Данное ПО может использоваться предприятиями, которым необходима усиленная ох
а как ты учитывала?

2020-03-16 15:14 UTC, AMyachev commented on docs/use-case.md
> +	Определять наличие дрона в данном радиусе;
с помощью двух микрофонов все 360 градусов не получится обработать

2020-03-16 16:34 UTC, Ann-Ageeva commented on docs/use-case.md
> +	Определять наличие дрона в данном радиусе;
если ты про определение сектора по тому методу, что ты скидывал, то может и нет. 
а вообще, почти любой микрофон обычный поймает звук по всему 360.

2020-03-16 16:38 UTC, Ann-Ageeva commented on docs/use-case.md
> +Для функционирования ПО детектирования необходимо: устройство записи звука, север, сеть, соединяющая устройства. Для осуществления детектирования online также понадобится мини-компьютер Raspberry Pi,
а, ну просто мы же сами хотели делать это на Raspberry PI, поэтому я про него и написала.

2020-03-17 08:21 UTC, AMyachev approved these changes

2020-03-17 08:21 UTC, merged