TZ
Ann-Ageeva/Sound-recognition pull request #16
Opened 2020-03-08 13:23 UTC by NikitaVashchuk

update TZ

2020-03-08 20:08 UTC, AMyachev requested changes

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +Работа в условиях умеренного фонового шума
Что значит умеренного? Нужно больше формализовать.

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +1.	Детектирование дронов по входящему небольшому оцифрованному звуковому фрагменту (сэмплу);
Насколько небольшого? Если нельзя уточнить, то лучше писать без этого слова.

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +2.	Определение позиции дрона на основе нескольких сэмплов, взятых с разных источников записи звука, в один и тот же промежуток времени.
Не надо уточнять здесь как мы будем находить направление. Просто сам факт того, что будем.

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +3.3.1.	Требования к информационным структурам и методам решения
Пока что можно добавить: Метод решения - глубокие нейронные сети с использование алгоритма [здесь будет название алгоритма для определения направления]

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +	Системные программные средства, используемые программой, должны быть 	представлены лицензионной локализованной версией операционной системы 	Windows и Linux.
Зачем писать лицензионные? Какая/ие версии windows(их много)? Наверное стоит говорить о семействе Unix систем с различными дистрибутивами (типа Ubuntu, Fedora, CentOS и тд), а не только о Linux

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +	Ориентировочная экономическая эффективность не рассчитываются. Аналогия не 	проводится ввиду уникальности предъявляемых требований к разработке.
В чём уникальность? Если не рассчитываются, то зачем писать?

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +Разработка должна быть проведена в три стадии:
Почему три, если потом перечисляется четыре?

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +На стадии разработки технического задания должен быть выполнен этап разработки, согласования и утверждения настоящего технического задания.
Это вообще не понял

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +На стадии внедрения должен быть выполнен этап разработки подготовка и передача программы.
Здесь уже разве нужна разработка?

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +На этапе разработки программной документации должна быть выполнена разработка программных документов в соответствии с требованиями к составу документации.
Зачем это писать? Из названия же вроде следует ...

2020-03-08 20:08 UTC, AMyachev commented on docs/project TZ.md
> +1.	разработка, согласование и утверждение и методики испытаний;
Этот пункт должен выполняться на этапе разработки тех документов, как считаешь?

2020-03-08 20:11 UTC, AMyachev commented
Ну и посмотри как этот файл отображается, через специальные программы для просмотра файлов формата markdown. Чтобы он там нормально отображался, нужно будет немного исходный текст подправить.

2020-03-16 15:39 UTC, NikitaVashchuk commented on docs/project TZ.md
> +Работа в условиях умеренного фонового шума
Исправлено

2020-03-16 15:39 UTC, NikitaVashchuk commented on docs/project TZ.md
> +1.	Детектирование дронов по входящему небольшому оцифрованному звуковому фрагменту (сэмплу);
Исправлено

2020-03-16 15:39 UTC, NikitaVashchuk commented on docs/project TZ.md
> +2.	Определение позиции дрона на основе нескольких сэмплов, взятых с разных источников записи звука, в один и тот же промежуток времени.
Исправлено

2020-03-16 15:39 UTC, NikitaVashchuk commented on docs/project TZ.md
> +3.3.1.	Требования к информационным структурам и методам решения
Исправлено

2020-03-16 15:43 UTC, NikitaVashchuk commented on docs/project TZ.md
> +	Ориентировочная экономическая эффективность не рассчитываются. Аналогия не 	проводится ввиду уникальности предъявляемых требований к разработке.
Не очень понятно о чем вообще тут можно говорить.
Пункт пока что удалим.

2020-03-16 15:43 UTC, NikitaVashchuk commented on docs/project TZ.md
> +Разработка должна быть проведена в три стадии:
Исправлено

2020-03-16 15:44 UTC, NikitaVashchuk commented on docs/project TZ.md
> +На стадии разработки технического задания должен быть выполнен этап разработки, согласования и утверждения настоящего технического задания.
Здесь подробно описываются стадии разработки описанные в 6.1.

2020-03-16 15:47 UTC, NikitaVashchuk commented on docs/project TZ.md
> +На стадии внедрения должен быть выполнен этап разработки подготовка и передача программы.
Убрал этот этап

2020-03-16 15:54 UTC, NikitaVashchuk commented on docs/project TZ.md
> +	Системные программные средства, используемые программой, должны быть 	представлены лицензионной локализованной версией операционной системы 	Windows и Linux.
Тут наверное надо написать вообще не про конкретные ОС и библиотеки, а именно общие требования к ним. То есть, то что в нашем случае они открытые и бесплатные.

2020-03-16 16:04 UTC, NikitaVashchuk commented on docs/project TZ.md
> +На этапе разработки программной документации должна быть выполнена разработка программных документов в соответствии с требованиями к составу документации.
Исправлено

2020-03-16 16:05 UTC, NikitaVashchuk commented on docs/project TZ.md
> +1.	разработка, согласование и утверждение и методики испытаний;
Мне кажется, это необходимо выполнить отдельным пунктом уже по завершению разработки, иначе любые правки могут привести к необходимости менять методику испытаний и проводить новые согласования.

2020-03-16 17:42 UTC, AMyachev commented on docs/project TZ.md
> +	Системные программные средства, используемые программой, должны быть 	представлены лицензионной локализованной версией операционной системы 	Windows и Linux.
ок

2020-03-16 17:42 UTC, AMyachev commented on docs/project TZ.md
> +	Ориентировочная экономическая эффективность не рассчитываются. Аналогия не 	проводится ввиду уникальности предъявляемых требований к разработке.
ок

2020-03-16 17:44 UTC, AMyachev commented on docs/project TZ.md
> +1.	разработка, согласование и утверждение и методики испытаний;
ок

2020-03-16 17:46 UTC, AMyachev commented
@NikitaVashchuk до сих пор невалидно отображается документ через github viewer

2020-03-16 21:28 UTC, AMyachev approved these changes

2020-03-16 21:29 UTC, merged