Client server
Ann-Ageeva/Sound-recognition pull request #31
Opened 2020-04-26 17:22 UTC by Merilla

Draft pull Request

2020-05-21 13:47 UTC, anmyachev commented on .travis.yml
> -os: linux
`.travis.yml` не надо удалять

2020-05-21 13:50 UTC, anmyachev commented on Readme.md
> +# You must be in Terminal (and you must select 1: cmd)
это можно сделать не только через `cmd`, но и через `powershell` или `mingw` консоль. Эту строчку надо удалить

2020-05-21 13:52 UTC, anmyachev commented on Readme.md
> +#conda install -c conda-forge NAME_PACK
Не нужно об этом писать здесь. Всю информацию о том, как работает та или иная команда можно узнать используя `--help` флаг

2020-05-21 13:53 UTC, anmyachev commented on Readme.md
> +#conda env update -f=environment.yml
то же самое (`--help` в помощь)

2020-05-21 13:54 UTC, anmyachev commented on docs/TZ.md
> -&nbsp;
Этот файл удалять не надо

2020-05-21 13:56 UTC, anmyachev commented
@Merilla нужно вернуть все файлы, которые были удалены

2020-05-21 13:57 UTC, anmyachev requested changes
@Merilla нужно пофиксить конфликты

2020-05-24 19:48 UTC, AMyachev requested changes
Надо починить CI

2020-05-25 07:01 UTC, Merilla commented
Done!

2020-05-25 07:03 UTC, anmyachev commented on docs/use-case.md
> -ПО «Dron sound detection»
Почему этот файл удалён?

2020-05-25 07:05 UTC, anmyachev commented on docs/use-case.md
> -ПО «Dron sound detection»
А также `tz-shablon.doc`, `pz-shablon.doc`, `nto-shablon,doc`, `docs/TZ.md` ?

2020-05-25 19:51 UTC, AMyachev approved these changes

2020-05-25 21:18 UTC, NikitaVashchuk approved these changes

2020-05-26 05:48 UTC, merged